language: node_js
node_js:
  - "node"

cache: npm

branches:
  only:
    - master

script:
  - cd client
  - npm install
  - npm run build

deploy:
  # Github pages
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: client/dist

  - provider: heroku
    skip_cleanup: true
    api_key:
      secret: $HEROKU_API