language: node_js
node_js:
  - "node"

cache: npm

branches:
  only:
    - master

page-script:
  - cd client
  - npm install
  - npm run build

deploy:
  # Github pages
  - provider: pages
    script: bash pages.sh
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: client/dist

  # Heroku
  #- provider: heroku
  #  skip_cleanup: true
  #  api_key:
  #    secure: $HEROKU_API
  #  app: tobias-portfolio-backend