language: node_js
node_js:
  - "node"

cache: npm

branches:
  only:
    - master



deploy:
  # Github pages
  - provider: pages
    script: 
    - cd client
    - npm install
    - npm run build
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: client/dist
    on:
      branch: master

  # Heroku
  - provider: heroku
    api_key: $HEROKU_API
    app: tobias-portfolio-backend
    script:
      - cd server
      - npm install
    on:
      branch: master