language: node_js
node_js:
  - "node"

cache: npm

branches:
  only:
    - master

script: 
  - cd client
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: client/dist
  on:
    branch: master